### ISSUE TITLE
Missing documentation: heat pump modbus setup

### ISSUE THREAD

**Issue by Bertk** [MadOne/weishaupt_modbus#1]
Unfortunately I have no access to English manuals for WSB 6 or 8.

German manual snippet.

>Zugriff mit Bus-Protokoll Modbus auf den Regler der Wärmepumpe.
>
>Wenn mit Modbus TCP auf den Regler zugegriffen wird, darf die Wärmepumpe nicht in ein (Heim-)Netzwerk integriert werden. Der Modbus TCP Client muss über eine Direktverbindung mit der Wärmepumpe kommunizieren, damit keine anderen Netzwerkteilnehmer auf die unverschlüsselte Modbus-Schnittstelle zugreifen können.
>
>Zugriff:
>
>* Aus (Werkseinstellung):\
> Zugriff ist deaktiviert.
>* Service:\
> Zugriff ist 60 Minuten möglich.
>* Ein:\
> Zugriff ist dauerhaft möglich.
>
>Netzwerk: IP-Adresse vom Netzwerkteilnehmer, der über Modbus auf den Regler zugreifen darf.
>Netzwerkmaske: Netzwerkmaske vom Netzwerkteilnehmer, der über Modbus auf den Regler zugreifen darf.

![image](https://github.com/user-attachments/assets/c82cdc13-8473-4193-a257-1b25340feccb)

Copilot English version

> Access with Modbus bus protocol to the heat pump controller.
>
>If accessing the controller via Modbus TCP, the heat pump must not be integrated into a (home) network. The Modbus TCP client must communicate with the heat pump via a direct connection to prevent other network participants from accessing the unencrypted Modbus interface.
>
>Access:
>- Off (Factory setting):\ 
>  Access is disabled.
>- Service:\
>  Access is possible for 60 minutes.
>- On:\
>  Access is permanently possible.
>
>Network: IP address of the network participant allowed to access the controller via Modbus.
>Network mask: Network mask of the network participant allowed to access the controller via Modbus.

![modbus-IPx](https://github.com/user-attachments/assets/d035411e-01f2-4580-a9f0-527d0f5717c1)

**Comment by MadOne** [comment]
At network ("Netzwerk") either place the IP of your HomeAssistant or leave the last place at 0 so the whole network is allowed (192.168.0.0).

**Comment by Bertk** [comment]
Thanks. I use the HomeAssistant IP but wanted to refer to the readme.md ToDo.

https://github.com/MadOne/weishaupt_modbus/blob/4e5dcd7c3b1b022bf9614af5920b87fe23b94a19/README.md?plain=1#L48

**Comment by MadOne** [comment]
I updated the readme.
I am a bit sad that i did not use any of your work but i find the official docs a bit confusing.
I hope you agree on this.
Thanks for your contribution, i really apreciate this!

**Comment by Bertk** [comment]
No problem. The information is now available.
