### ISSUE TITLE
Missing parameters for "Heizkreis" and "Warm water"

### ISSUE THREAD

**Issue by misterbond007** [MadOne/weishaupt_modbus#4]
The following parameters are missing for Heizkreis (they are not being displayed in Home Assistant):

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/Emanuel/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/Emanuel/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link=blue vlink=purple>

Bezeichnung | Format | Modbus
-- | -- | -- 
Raumsolltemperatur Komfort | FormatSollwert | 41 105
Raumsolltemperatur Normal | FormatSollwert | 41 106
Raumsolltemperatur Absenk | FormatSollwert | 41 107
Heizkennlinie | FormatHeizkreisKennlinie | 41 108
Sommer Winter Umschaltung | FormatHeizrkeisSommer | 41 109
Heizen Konstanttemperatur | FormatHeizkreisKonstantTag | 41 110
Heizen Konstanttemp Absenk | FormatHeizkreisKonstantNacht | 41 111
Kühlen Konstanttemperatur | FormatSollwert | 41 112

</body>

</html>

The following parameters are missing for Warm water (they are not being displayed in Home Assistant):

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/Emanuel/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/Emanuel/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link=blue vlink=purple>

Bezeichnung | Format | Modbus
-- | -- | -- 
Warmwassersolltemperatur | FormatSollwert | 32 101
Warmwassertemperatur | FormatSensor | 32 102
Konfiguration  | 0 = Aus 1 = Umlenkventil 8 = Pumpe | 42 101
Warmwasser Push | 0 = AUS, 5 ... 240 MIN | 42 102
SG Ready Anhebung | FormatSensor | 42 105

</body>

</html>

**Comment by MadOne** [comment]
Hi, 
thanks for your bug report.
There is a fork of my integration at : https://github.com/OStrama/weishaupt_modbus
I think his approach is far superor to mine. I think this integration will not be developed anymore.

**Comment by misterbond007** [comment]
Thank you very much!

**Comment by MadOne** [comment]
Konfiguration should be added with 2f5c516c8b32ce4d93c7849d091390db2d0d1d53
The other Values should already be present.
