### ISSUE TITLE
No "Betriebsart" entity

### ISSUE THREAD

**Issue by misterbond007** [MadOne/weishaupt_modbus#5]
After changing your

    @property
    def HK_Betriebsart(self):
        val = self.WWP.read_holding_registers(41103, slave=1).registers[0]

        match val:
            case 0:
                return "AUTOMATIK"
            case 1:
                return "KOMFORT"
            case 2:
                return "NORMAL"
            case 3:
                return "ABSENKBETRIEB"
            case 5:
                return "STANDBY"

to 

    @property
    def HK_Betriebsart(self):

        match val:
            case 0:
                return "AUTOMATIK"
            case 1:
                return "KOMFORT"
            case 2:
                return "NORMAL"
            case 3:
                return "ABSENKBETRIEB"
            case 5:
                return "STANDBY"
        self.WWP.write_register(41103, return_value, slave=1)

I was able to the set the Betriebsart in Home Assistant.

**Comment by MadOne** [comment]
Hi, 
thanks for your bug report.
There is a fork of my integration at : https://github.com/OStrama/weishaupt_modbus
I think his approach is far superor to mine. I think this integration will not be developed anymore.

**Comment by misterbond007** [comment]
Thank you very much!

**Comment by MadOne** [comment]
Please talk to the owner of the fork.

**Comment by MadOne** [comment]
Fixed with ee260ef0475df631a77bc796c66d23e86a49702d
