### ISSUE TITLE
Volumenstrom Values are wrong

### ISSUE THREAD

**Issue by john92648** [MadOne/weishaupt_modbus#7]
Hi, I installed yor Repository and all is fine, only the numbers for the Volumenstrom are different with the Original WEM Portal.
Mit freundlichen Grüßen
John92648

**Comment by MadOne** [comment]
What Values are you talking about?
I am quite sure i have not implemented such values yet. ;)

**Comment by john92648** [comment]
Hi, maybe I used the wrong application.
![Bildschirmfoto 2024-10-09 um 08 34 18](https://github.com/user-attachments/assets/4a9ce079-c39a-4eaf-b6b5-2be791ce7834)
I used integration from 
![Bildschirmfoto 2024-10-09 um 08 40 19](https://github.com/user-attachments/assets/7fbb8d6a-3903-4e70-b84f-652c559d5b67)
Mit freundlichen Grüßen
john92648

**Comment by MadOne** [comment]
Are you using the fork of OStrama?

**Comment by john92648** [comment]
I tried both, but since Weishaupt WEM Portal is working again, I switched back to Weishaupt WEM Portal.
Thanks for your support.
