### ISSUE TITLE
Missing attribute state_class for sensor.energy_today entity

### ISSUE THREAD

**Issue by Bertk** [MadOne/weishaupt_modbus#9]
The `sensor.energy_today` cannot be added to energy dashboard [individual devices because](https://www.home-assistant.io/docs/energy/individual-devices/) because state_class is not defined.

`_attr_state_class = SensorStateClass.TOTAL_INCREASING`

Adding this line to sensor.py (line 690) solves the issue.

https://github.com/MadOne/weishaupt_modbus/blob/ac8510a3557dc975d272914f20297fc806a7e498/custom_components/weishaupt_modbus/sensor.py#L682C1-L689C50

>[!IMPORTANT]
>This git repository is not maintained anymore but this helpful information should be shared anyway. You have to add one line and can use the heat pump usage of electrical energy in the dashboard.

**Comment by MadOne** [comment]
Hi,
as far is i know this is thermal energy.

**Comment by Bertk** [comment]
OK. I will close this issue. The naming is of course a key information for the meaning. 

![image](https://github.com/user-attachments/assets/267e1448-52ac-4ef0-b8d4-23b2f08dda59)

![image](https://github.com/user-attachments/assets/6c0d8fa9-e705-4749-9cd4-3a747af8e9b8)

https://docs.google.com/spreadsheets/d/1EZ3QgyB41xaXo4B5CfZe0Pi8KPwzIGzK/edit?gid=811694071#gid=811694071

**Comment by MadOne** [comment]
I think this value is NOT Total increasing, as it is reset every day.

You are right, the name is not perfect.
I just took the name from Weishaupt.

**Comment by Bertk** [comment]
The daily energie usage is OK for the indivisual device of energy dashboard. Energy dashboard shows the energie usage per day.

[STATE_CLASS_TOTAL_INCREASING explained](https://developers.home-assistant.io/blog/2021/08/16/state_class_total/)
